"""empty message

Revision ID: 03c947777869
Revises: 69c232d33aa9
Create Date: 2026-03-20 23:54:22.445481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c947777869'
down_revision = '69c232d33aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('favorite_planet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_planet', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
