"""empty message

Revision ID: 2a3f88e59670
Revises: b24408a103ca
Create Date: 2026-03-21 00:19:13.150185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3f88e59670'
down_revision = 'b24408a103ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_planet_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planet', ['home_planet_id'], ['id'])
        batch_op.drop_column('home_planet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_planet', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('home_planet_id')

    # ### end Alembic commands ###
