"""empty message

Revision ID: 4637ec5c51c7
Revises: a9f1bfc49935
Create Date: 2026-03-20 01:57:22.301198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4637ec5c51c7'
down_revision = 'a9f1bfc49935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorite_planets')
    op.drop_table('user_favorite_characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_characters',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='user_favorite_characters_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_favorite_characters_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'character_id', name='user_favorite_characters_pkey')
    )
    op.create_table('user_favorite_planets',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='user_favorite_planets_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_favorite_planets_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'planet_id', name='user_favorite_planets_pkey')
    )
    # ### end Alembic commands ###
