"""empty message

Revision ID: 533e8cdaf035
Revises: b617cf165a22
Create Date: 2026-03-20 00:39:51.478542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533e8cdaf035'
down_revision = 'b617cf165a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorite_Character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('characters_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Favorite_Planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planets_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fav_planet_id', sa.Integer(), nullable=False),
    sa.Column('fav_character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_character_id'], ['Favorite_Character.id'], ),
    sa.ForeignKeyConstraint(['fav_planet_id'], ['Favorite_Planet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('favorite__character')
    op.drop_table('user')
    op.drop_table('favorite__planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], name='favorite__planet_planets_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite__planet_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_table('favorite__character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('characters_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], name='favorite__character_characters_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite__character_pkey')
    )
    op.drop_table('User')
    op.drop_table('Favorite_Planet')
    op.drop_table('Favorite_Character')
    # ### end Alembic commands ###
