"""empty message

Revision ID: 69c232d33aa9
Revises: 5834e2b13994
Create Date: 2026-03-20 23:37:44.083130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c232d33aa9'
down_revision = '5834e2b13994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_fav_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint(
            'user_fav_character_id_fkey', type_='foreignkey')
        batch_op.drop_column('fav_planet_id')
        batch_op.drop_column('fav_character_id')

    op.drop_table('Favorite_Character')
    op.drop_table('Favorite_Planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_character_id',
                            sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(
            sa.Column('fav_planet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_fav_character_id_fkey', 'Favorite_Character', [
                                    'fav_character_id'], ['id'])
        batch_op.create_foreign_key('user_fav_planet_id_fkey', 'Favorite_Planet', [
                                    'fav_planet_id'], ['id'])

    op.create_table('Favorite_Planet',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('planets_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['planets_id'], ['planets.id'], name='Favorite_Planet_planets_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='Favorite_Planet_pkey')
                    )
    op.create_table('Favorite_Character',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('characters_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['characters_id'], [
                        'characters.id'], name='Favorite_Character_characters_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'id', name='Favorite_Character_pkey')
                    )
    # ### end Alembic commands ###
