"""empty message

Revision ID: a9f1bfc49935
Revises: 533e8cdaf035
Create Date: 2026-03-20 01:37:53.148978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f1bfc49935'
down_revision = '533e8cdaf035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fav_planet_id', sa.Integer(), nullable=False),
    sa.Column('fav_character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_character_id'], ['Favorite_Character.id'], ),
    sa.ForeignKeyConstraint(['fav_planet_id'], ['Favorite_Planet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_favorite_characters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    op.create_table('user_favorite_planets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fav_planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fav_character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fav_character_id'], ['Favorite_Character.id'], name='User_fav_character_id_fkey'),
    sa.ForeignKeyConstraint(['fav_planet_id'], ['Favorite_Planet.id'], name='User_fav_planet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    sa.UniqueConstraint('email', name='User_email_key')
    )
    op.drop_table('user_favorite_planets')
    op.drop_table('user_favorite_characters')
    op.drop_table('user')
    # ### end Alembic commands ###
