"""empty message

Revision ID: af07952325c4
Revises: c253571e8061
Create Date: 2026-03-20 00:20:36.233343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af07952325c4'
down_revision = 'c253571e8061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite__character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'characters', ['characters_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite__character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('characters_id')

    # ### end Alembic commands ###
