"""empty message

Revision ID: b24408a103ca
Revises: 03c947777869
Create Date: 2026-03-20 23:59:35.025564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24408a103ca'
down_revision = '03c947777869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('char_image', sa.String(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(
                        length=555), nullable=False),
                    sa.Column('home_planet', sa.String(
                        length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('planet',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('terrain', sa.String(
                        length=500), nullable=False),
                    sa.Column('planet_image', sa.String(
                        length=500), nullable=False),
                    sa.Column('population', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    # Copy data from old tables to new tables
    op.execute('INSERT INTO character SELECT * FROM characters')
    op.execute('INSERT INTO planet SELECT * FROM planets')

    with op.batch_alter_table('user_favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint(
            'user_favorite_characters_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(
            None, 'character', ['character_id'], ['id'])

    with op.batch_alter_table('user_favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint(
            'user_favorite_planets_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])

    op.drop_table('characters')
    op.drop_table('planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'user_favorite_planets_planet_id_fkey', 'planets', ['planet_id'], ['id'])

    with op.batch_alter_table('user_favorite_characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(
            'user_favorite_characters_character_id_fkey', 'characters', ['character_id'], ['id'])

    op.create_table('planets',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('terrain', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=False),
                    sa.Column('planet_image', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=False),
                    sa.Column('population', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='planets_pkey')
                    )
    op.create_table('characters',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('char_image', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.Column('age', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(length=555),
                              autoincrement=False, nullable=False),
                    sa.Column('home_planet', sa.VARCHAR(length=50),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='characters_pkey')
                    )
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
