"""empty message

Revision ID: c253571e8061
Revises: 6cdd9ce11145
Create Date: 2026-03-20 00:13:04.158499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c253571e8061'
down_revision = '6cdd9ce11145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('favorite_character')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_character', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.drop_table('favorite__character')
    # ### end Alembic commands ###
